// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.3
// source: muxcore/metadata/v1/metadata.proto

package metadatav1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataService_Search_FullMethodName               = "/muxcore.metadata.v1.MetadataService/Search"
	MetadataService_GetMovieDetails_FullMethodName      = "/muxcore.metadata.v1.MetadataService/GetMovieDetails"
	MetadataService_GetTVDetails_FullMethodName         = "/muxcore.metadata.v1.MetadataService/GetTVDetails"
	MetadataService_GetSeasonDetails_FullMethodName     = "/muxcore.metadata.v1.MetadataService/GetSeasonDetails"
	MetadataService_GetEpisodeDetails_FullMethodName    = "/muxcore.metadata.v1.MetadataService/GetEpisodeDetails"
	MetadataService_GetCollection_FullMethodName        = "/muxcore.metadata.v1.MetadataService/GetCollection"
	MetadataService_GetConfiguration_FullMethodName     = "/muxcore.metadata.v1.MetadataService/GetConfiguration"
	MetadataService_ListTrending_FullMethodName         = "/muxcore.metadata.v1.MetadataService/ListTrending"
	MetadataService_ListPopular_FullMethodName          = "/muxcore.metadata.v1.MetadataService/ListPopular"
	MetadataService_ListSimilar_FullMethodName          = "/muxcore.metadata.v1.MetadataService/ListSimilar"
	MetadataService_ListRecommendations_FullMethodName  = "/muxcore.metadata.v1.MetadataService/ListRecommendations"
	MetadataService_FindByExternalID_FullMethodName     = "/muxcore.metadata.v1.MetadataService/FindByExternalID"
	MetadataService_GetAlternativeTitles_FullMethodName = "/muxcore.metadata.v1.MetadataService/GetAlternativeTitles"
)

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetadataService is the gRPC surface for MetadataProvider implementers.
type MetadataServiceClient interface {
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetMovieDetails(ctx context.Context, in *GetMovieDetailsRequest, opts ...grpc.CallOption) (*GetMovieDetailsResponse, error)
	GetTVDetails(ctx context.Context, in *GetTVDetailsRequest, opts ...grpc.CallOption) (*GetTVDetailsResponse, error)
	GetSeasonDetails(ctx context.Context, in *GetSeasonDetailsRequest, opts ...grpc.CallOption) (*GetSeasonDetailsResponse, error)
	GetEpisodeDetails(ctx context.Context, in *GetEpisodeDetailsRequest, opts ...grpc.CallOption) (*GetEpisodeDetailsResponse, error)
	GetCollection(ctx context.Context, in *GetCollectionRequest, opts ...grpc.CallOption) (*GetCollectionResponse, error)
	GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error)
	ListTrending(ctx context.Context, in *ListTrendingRequest, opts ...grpc.CallOption) (*ListTrendingResponse, error)
	ListPopular(ctx context.Context, in *ListPopularRequest, opts ...grpc.CallOption) (*ListPopularResponse, error)
	ListSimilar(ctx context.Context, in *ListSimilarRequest, opts ...grpc.CallOption) (*ListSimilarResponse, error)
	ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error)
	FindByExternalID(ctx context.Context, in *FindByExternalIDRequest, opts ...grpc.CallOption) (*FindByExternalIDResponse, error)
	GetAlternativeTitles(ctx context.Context, in *GetAlternativeTitlesRequest, opts ...grpc.CallOption) (*GetAlternativeTitlesResponse, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, MetadataService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetMovieDetails(ctx context.Context, in *GetMovieDetailsRequest, opts ...grpc.CallOption) (*GetMovieDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMovieDetailsResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetMovieDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetTVDetails(ctx context.Context, in *GetTVDetailsRequest, opts ...grpc.CallOption) (*GetTVDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTVDetailsResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetTVDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetSeasonDetails(ctx context.Context, in *GetSeasonDetailsRequest, opts ...grpc.CallOption) (*GetSeasonDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSeasonDetailsResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetSeasonDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetEpisodeDetails(ctx context.Context, in *GetEpisodeDetailsRequest, opts ...grpc.CallOption) (*GetEpisodeDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEpisodeDetailsResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetEpisodeDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetCollection(ctx context.Context, in *GetCollectionRequest, opts ...grpc.CallOption) (*GetCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectionResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetConfiguration(ctx context.Context, in *GetConfigurationRequest, opts ...grpc.CallOption) (*GetConfigurationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigurationResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetConfiguration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListTrending(ctx context.Context, in *ListTrendingRequest, opts ...grpc.CallOption) (*ListTrendingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrendingResponse)
	err := c.cc.Invoke(ctx, MetadataService_ListTrending_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListPopular(ctx context.Context, in *ListPopularRequest, opts ...grpc.CallOption) (*ListPopularResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPopularResponse)
	err := c.cc.Invoke(ctx, MetadataService_ListPopular_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListSimilar(ctx context.Context, in *ListSimilarRequest, opts ...grpc.CallOption) (*ListSimilarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSimilarResponse)
	err := c.cc.Invoke(ctx, MetadataService_ListSimilar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListRecommendations(ctx context.Context, in *ListRecommendationsRequest, opts ...grpc.CallOption) (*ListRecommendationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRecommendationsResponse)
	err := c.cc.Invoke(ctx, MetadataService_ListRecommendations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) FindByExternalID(ctx context.Context, in *FindByExternalIDRequest, opts ...grpc.CallOption) (*FindByExternalIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindByExternalIDResponse)
	err := c.cc.Invoke(ctx, MetadataService_FindByExternalID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetAlternativeTitles(ctx context.Context, in *GetAlternativeTitlesRequest, opts ...grpc.CallOption) (*GetAlternativeTitlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlternativeTitlesResponse)
	err := c.cc.Invoke(ctx, MetadataService_GetAlternativeTitles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
// All implementations must embed UnimplementedMetadataServiceServer
// for forward compatibility.
//
// MetadataService is the gRPC surface for MetadataProvider implementers.
type MetadataServiceServer interface {
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	GetMovieDetails(context.Context, *GetMovieDetailsRequest) (*GetMovieDetailsResponse, error)
	GetTVDetails(context.Context, *GetTVDetailsRequest) (*GetTVDetailsResponse, error)
	GetSeasonDetails(context.Context, *GetSeasonDetailsRequest) (*GetSeasonDetailsResponse, error)
	GetEpisodeDetails(context.Context, *GetEpisodeDetailsRequest) (*GetEpisodeDetailsResponse, error)
	GetCollection(context.Context, *GetCollectionRequest) (*GetCollectionResponse, error)
	GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error)
	ListTrending(context.Context, *ListTrendingRequest) (*ListTrendingResponse, error)
	ListPopular(context.Context, *ListPopularRequest) (*ListPopularResponse, error)
	ListSimilar(context.Context, *ListSimilarRequest) (*ListSimilarResponse, error)
	ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error)
	FindByExternalID(context.Context, *FindByExternalIDRequest) (*FindByExternalIDResponse, error)
	GetAlternativeTitles(context.Context, *GetAlternativeTitlesRequest) (*GetAlternativeTitlesResponse, error)
	mustEmbedUnimplementedMetadataServiceServer()
}

// UnimplementedMetadataServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataServiceServer struct{}

func (UnimplementedMetadataServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedMetadataServiceServer) GetMovieDetails(context.Context, *GetMovieDetailsRequest) (*GetMovieDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovieDetails not implemented")
}
func (UnimplementedMetadataServiceServer) GetTVDetails(context.Context, *GetTVDetailsRequest) (*GetTVDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTVDetails not implemented")
}
func (UnimplementedMetadataServiceServer) GetSeasonDetails(context.Context, *GetSeasonDetailsRequest) (*GetSeasonDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSeasonDetails not implemented")
}
func (UnimplementedMetadataServiceServer) GetEpisodeDetails(context.Context, *GetEpisodeDetailsRequest) (*GetEpisodeDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEpisodeDetails not implemented")
}
func (UnimplementedMetadataServiceServer) GetCollection(context.Context, *GetCollectionRequest) (*GetCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollection not implemented")
}
func (UnimplementedMetadataServiceServer) GetConfiguration(context.Context, *GetConfigurationRequest) (*GetConfigurationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfiguration not implemented")
}
func (UnimplementedMetadataServiceServer) ListTrending(context.Context, *ListTrendingRequest) (*ListTrendingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrending not implemented")
}
func (UnimplementedMetadataServiceServer) ListPopular(context.Context, *ListPopularRequest) (*ListPopularResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPopular not implemented")
}
func (UnimplementedMetadataServiceServer) ListSimilar(context.Context, *ListSimilarRequest) (*ListSimilarResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSimilar not implemented")
}
func (UnimplementedMetadataServiceServer) ListRecommendations(context.Context, *ListRecommendationsRequest) (*ListRecommendationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListRecommendations not implemented")
}
func (UnimplementedMetadataServiceServer) FindByExternalID(context.Context, *FindByExternalIDRequest) (*FindByExternalIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByExternalID not implemented")
}
func (UnimplementedMetadataServiceServer) GetAlternativeTitles(context.Context, *GetAlternativeTitlesRequest) (*GetAlternativeTitlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAlternativeTitles not implemented")
}
func (UnimplementedMetadataServiceServer) mustEmbedUnimplementedMetadataServiceServer() {}
func (UnimplementedMetadataServiceServer) testEmbeddedByValue()                         {}

// UnsafeMetadataServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataServiceServer will
// result in compilation errors.
type UnsafeMetadataServiceServer interface {
	mustEmbedUnimplementedMetadataServiceServer()
}

func RegisterMetadataServiceServer(s grpc.ServiceRegistrar, srv MetadataServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetadataServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataService_ServiceDesc, srv)
}

func _MetadataService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetMovieDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovieDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetMovieDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetMovieDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetMovieDetails(ctx, req.(*GetMovieDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetTVDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTVDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetTVDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetTVDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetTVDetails(ctx, req.(*GetTVDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetSeasonDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSeasonDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetSeasonDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetSeasonDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetSeasonDetails(ctx, req.(*GetSeasonDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetEpisodeDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEpisodeDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetEpisodeDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetEpisodeDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetEpisodeDetails(ctx, req.(*GetEpisodeDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetCollection(ctx, req.(*GetCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetConfiguration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigurationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetConfiguration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetConfiguration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetConfiguration(ctx, req.(*GetConfigurationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListTrending_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrendingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListTrending(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ListTrending_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListTrending(ctx, req.(*ListTrendingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListPopular_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPopularRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListPopular(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ListPopular_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListPopular(ctx, req.(*ListPopularRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListSimilar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSimilarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListSimilar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ListSimilar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListSimilar(ctx, req.(*ListSimilarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListRecommendations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListRecommendations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_ListRecommendations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListRecommendations(ctx, req.(*ListRecommendationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_FindByExternalID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByExternalIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).FindByExternalID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_FindByExternalID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).FindByExternalID(ctx, req.(*FindByExternalIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetAlternativeTitles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlternativeTitlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetAlternativeTitles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataService_GetAlternativeTitles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetAlternativeTitles(ctx, req.(*GetAlternativeTitlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataService_ServiceDesc is the grpc.ServiceDesc for MetadataService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "muxcore.metadata.v1.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _MetadataService_Search_Handler,
		},
		{
			MethodName: "GetMovieDetails",
			Handler:    _MetadataService_GetMovieDetails_Handler,
		},
		{
			MethodName: "GetTVDetails",
			Handler:    _MetadataService_GetTVDetails_Handler,
		},
		{
			MethodName: "GetSeasonDetails",
			Handler:    _MetadataService_GetSeasonDetails_Handler,
		},
		{
			MethodName: "GetEpisodeDetails",
			Handler:    _MetadataService_GetEpisodeDetails_Handler,
		},
		{
			MethodName: "GetCollection",
			Handler:    _MetadataService_GetCollection_Handler,
		},
		{
			MethodName: "GetConfiguration",
			Handler:    _MetadataService_GetConfiguration_Handler,
		},
		{
			MethodName: "ListTrending",
			Handler:    _MetadataService_ListTrending_Handler,
		},
		{
			MethodName: "ListPopular",
			Handler:    _MetadataService_ListPopular_Handler,
		},
		{
			MethodName: "ListSimilar",
			Handler:    _MetadataService_ListSimilar_Handler,
		},
		{
			MethodName: "ListRecommendations",
			Handler:    _MetadataService_ListRecommendations_Handler,
		},
		{
			MethodName: "FindByExternalID",
			Handler:    _MetadataService_FindByExternalID_Handler,
		},
		{
			MethodName: "GetAlternativeTitles",
			Handler:    _MetadataService_GetAlternativeTitles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "muxcore/metadata/v1/metadata.proto",
}
